### ISSUE TITLE
Could you agree PR with install example_configs from prometheus / jmx_exporter ?

### ISSUE THREAD

**Issue by patsevanton** [andrewrothstein/ansible-prometheus_jmx_exporter#1]
Hello! Thanks for role jmx_exporter

Could you agree PR with install example_configs from [prometheus / jmx_exporter](https://github.com/prometheus/jmx_exporter/tree/master/example_configs) ?

**Comment by andrewrothstein** [comment]
No thank you. I think that kind of configuration belongs in a more JVM app specific configuration role.
